on:
  push:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "!.github/workflows/test-suite.yaml"
    branches:
      - master
      - release-**

name: Branch Merge Build
permissions:
    contents: write
    id-token: write
jobs:
  build-amd64:
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},image=ubuntu22-full-x64,hdd=64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        version: v0.16.0
        driver: docker-container
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
    - name: Export Cache Env Vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
    - name: Install Dapper
      run: |
        curl -sL https://github.com/brandond/dapper/releases/download/v0.7.0-bd5/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper
    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/aws-access-key-id/credentials token | AWS_ACCESS_KEY_ID ;
          secret/data/github/repo/${{ github.repository }}/aws-secret-access-key/credentials token | AWS_SECRET_ACCESS_KEY ;
    - name: Build
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make dapper-ci
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    - name: Test
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make test
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
  build-arm64:
    runs-on: runs-on,runner=8cpu-linux-arm64,run-id=${{ github.run_id }},image=ubuntu22-full-arm64,hdd=64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        version: v0.16.0
        driver: docker-container
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
    - name: Export Cache Env Vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
    - name: Install Dapper
      run: |
        curl -sL https://github.com/brandond/dapper/releases/download/v0.7.0-bd5/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper
    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/aws-access-key-id/credentials token | AWS_ACCESS_KEY_ID ;
          secret/data/github/repo/${{ github.repository }}/aws-secret-access-key/credentials token | AWS_SECRET_ACCESS_KEY ;
    - name: Build
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make dapper-ci
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
