on:
  push:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "!.github/workflows/test-suite.yaml"
    tags:
    - "v*"

env:
  GITHUB_ACTION_TAG: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
  
name: Release
permissions:
    contents: write
    id-token: write
jobs:
  release-amd64:
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},image=ubuntu22-full-x64,hdd=256
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dapper
      run: |
        curl -sL https://github.com/brandond/dapper/releases/download/v0.7.0-bd5/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper

    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        version: v0.16.0
        driver: docker-container
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]

    - name: Export Cache Env Vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

    - name: Validate Release
      run: |
       dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make validate-release
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}

    - name: Build
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make dapper-ci
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    
    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;

    - name: Package Images
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make package-images
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    
    - name: Scan Images
      continue-on-error: true
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make scan-images
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    
    - name: Test
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make test
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}

    - name: Publish Image Runtime
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make publish-image-runtime
      env:
        DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
        GITHUB_ACTION_TAG: ${{ github.ref_name }}
    
    - name: Checksum Artifacts
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make checksum
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
        GITHUB_ACTION_TAG: ${{ github.ref_name }}

    - name: Publish Artifacts
      run: |
        gh release upload ${{ github.ref_name }} dist/artifacts/*
  release-arm64:
    runs-on: runs-on,runner=8cpu-linux-arm64,run-id=${{ github.run_id }},image=ubuntu22-full-arm64,hdd=256
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        version: v0.16.0
        driver: docker-container
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]

    - name: Export Cache Env Vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

    - name: Install Dapper
      run: |
        curl -sL https://github.com/brandond/dapper/releases/download/v0.7.0-bd5/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper

    - name: Validate Release
      run: |
       dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make validate-release
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}

    - name: Build
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make dapper-ci
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    
    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;

    - name: Package Images
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make package-images
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
    
    - name: Scan Images
      continue-on-error: true
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make scan-images
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}

    - name: Publish Image Runtime
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make publish-image-runtime
      env:
        DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
        GITHUB_ACTION_TAG: ${{ github.ref_name }}

    - name: Checksum
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make checksum
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
        GITHUB_ACTION_TAG: ${{ github.ref_name }}

    - name: Publish Artifacts
      run: |
        gh release upload ${{ github.ref_name }} dist/artifacts/*
  dispatch:
    needs: [release-amd64, release-arm64]
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},image=ubuntu22-full-x64,hdd=64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up buildx
      uses: docker/setup-buildx-action@v3
      id: buildx
      with:
        version: v0.16.0
        driver: docker-container
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]

    - name: Export Cache Env Vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])

    - name: Install Dapper
      run: |
        curl -sL https://github.com/brandond/dapper/releases/download/v0.7.0-bd5/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper
    
    - name: "Read secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/pat_username/credentials token | PAT_USERNAME ;

    - name: Dispatch
      run: |
        dapper -f Dockerfile --bake --cache-from type=gha --cache-to type=gha,ignore-error=true,mode=max --target dapper make dispatch
      env:
        PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATH_USERNAME: ${{ env.PAT_USERNAME }}
        GITHUB_ACTION_TAG: ${{ env.GITHUB_ACTION_TAG }}
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
